### ISSUE TITLE
Publishing on the PyPI

### ISSUE THREAD

**Issue by isidentical** [we-like-parsers/pegen#1]
Pegen's Python parser generator is really cool, and also very [useful](https://github.com/isidentical/pyasdl/blob/master/pyasdl/parser.py) though the version on the PyPI seems not sync with the upstream version under Tools/peg_generator. It is possible now to just clone CPython and install it though not very feasible. Or the other way would be, after generating the parser just hosting `pegen/parser.py` / `pegen/tokenizer.py` under the project (which is what I do now) though it is not a very good solution either. I think it would be really amazing if we host this package on the PyPI (maybe with automating some stuff on the GH actions to clone CPython, check if anything changed under `Tools/peg_generator`, and sync it with here and open an issue to notify the maintainers that they should make a release). If any help needed, I can try to assist.

**Comment by pablogsal** [comment]
I renamed the old repo to https://github.com/we-like-parsers/pegen_experiments and I have created https://github.com/we-like-parsers/pegen with some initial scaffolding, also updating the code from CPython

**Comment by lysnikolaou** [comment]
Should I start removing stuff? The way I see it, we probably can remove anything not related to the python generator. `docs`, some of the `scripts` and some of the `tests` can certainly go. We can wrap the thing around a nicer API next and maybe improve the README?

**Comment by gvanrossum** [comment]
Do I need to fix the links in my blog posts on Medium? Some of those link
to the examples in this repo.

**Comment by pablogsal** [comment]
> Do I need to fix the links in my blog posts on Medium? Some of those link to the examples in this repo.

Oh, good point! I will move the files back so the links are still valid.

**Comment by pablogsal** [comment]
> Should I start removing stuff? The way I see it, we probably can remove anything not related to the python generator. `docs`, some of the `scripts` and some of the `tests` can certainly go. We can wrap the thing around a nicer API/command-line utility next and maybe improve the README?

I did some general removal already and I prepared the package with some stuff for easier testing of the pypi packages, but feel free to continue improving and cleaning stuff :)

**Comment by pablogsal** [comment]
> Do I need to fix the links in my blog posts on Medium? Some of those link to the examples in this repo.

Interesting. I checked the links in your blog and GitHub seems smart enough to redirect to the previous (now renamed) repo!

**Comment by lysnikolaou** [comment]
This has been there since 2013! https://github.blog/2013-05-16-repository-redirects-are-here/

**Comment by MatthieuDartiailh** [comment]
The first release is online since September 7th
