### ISSUE TITLE
Redundant semicolon in python_generator.py?

### ISSUE THREAD

**Issue by yf-yang** [we-like-parsers/pegen#105]
https://github.com/we-like-parsers/pegen/commit/e28fe4fb1972c55af5ddb6a7bdd9cba4ea072b81#r149797779

I don't know if this `;` has any special meaning here. From the generated parser script and from the commit diff, it looks like a typo.

**Comment by yf-yang** [comment]
cc @MatthieuDartiailh

**Comment by lysnikolaou** [comment]
It's probably a typo. @yf-yang Feel free to open a PR to fix this if you want.
