### ISSUE TITLE
Is formatting subheader required ?

### ISSUE THREAD

**Issue by MatthieuDartiailh** [we-like-parsers/pegen#13]
Currently both the header and the subheader are formatted using `.format(filename=filename)`. 

I agree it is useful to include the name of the grammar in the header, however doing the same for the subheader does not seem necessary and make the use of any kind of formatting operation (for error messages for example) painful due to the need to use double {} to escape the first formatting.

Would the authors be favorable to removing the formatting of the subheader.

**Comment by pablogsal** [comment]
> Would the authors be favorable to removing the formatting of the subheader.

I would be positive, I think it makes sense

**Comment by MatthieuDartiailh** [comment]
I will make a PR shortly.

**Comment by MatthieuDartiailh** [comment]
See #15
