### ISSUE TITLE
Status of this project?

### ISSUE THREAD

**Issue by sirex** [we-like-parsers/pegen#248]
README.md says "This is a work in progress", `python -m pegen --help` says "Experimental PEG-like parser generator". But on the other hand, [Python 3.9 is going to use it by default](https://docs.python.org/3.9/whatsnew/3.9.html#pep-617-new-parser).

So is pegen is still in progress and experimental or production ready and stable?

Also, which version is considered to be upstream? [This](https://github.com/we-like-parsers/pegen) repository or a [copy](https://github.com/python/cpython/tree/master/Tools/peg_generator) in python/cpython?

**Comment by pablogsal** [comment]
> So is pegen is still in progress and experimental or production ready and stable?

This repo was used during the development of pegen (and is still used for the development of future features of the parser), but the authoritative version is the one included in CPython

> So is pegen is still in progress and experimental or production ready and stable?

Given that 3.9 will be shipped next Monday with pegen by default, I would say is stable and ready 😉 

> Also, which version is considered to be upstream? [This](https://github.com/we-like-parsers/pegen) repository or a [copy](https://github.com/python/cpython/tree/master/Tools/peg_generator) in python/cpython?

By definition, the version upstream is the one included in python/cpython
