### ISSUE TITLE
Advice request - general purpose parser generator?

### ISSUE THREAD

**Issue by alakeev** [we-like-parsers/pegen#28]
Hi, in your series you've mentions that:
> The result may not be a great general-purpose PEG parser generator — there are already many of those (e.g. TatSu is written in Python and generates Python code)

After nine episodes and several years of developing pegen, if you were to define a grammar and generate a parser for a completely different language, would you do it using Pegen or stick to a third-party solution like TatSu?

**Comment by pablogsal** [comment]
`pegen` is specially tailored to the Python language and although is quite general, it has some level of coupling with the Python tokenizer, so in general unless your language is very similar to Python I would recommend something more generic like TatSu

**Comment by alakeev** [comment]
Thank you for the answer, tokenizer was exactly what bothered me
