### ISSUE TITLE
Metaparser cannot be regenerated since 74eb1c37c8c2fab2767a349e9e3fb9bbcf1edd6e

### ISSUE THREAD

**Issue by pablogsal** [we-like-parsers/pegen#32]
Unfortunately, seems that we cannot regenerate the metaparser (make regen-metaparser) since commit 74eb1c37c8c2fab2767a349e9e3fb9bbcf1edd6e.

**Comment by pablogsal** [comment]
@MatthieuDartiailh can you give it a look?

**Comment by pablogsal** [comment]
Somehow it doesn't like that "memo" is a keyword

**Comment by pablogsal** [comment]
The problem is that this condition is wrong:

```
if tok.type == token.NAME and tok.string not in self.KEYWORDS:
```

that has to be liften in the actions

**Comment by pablogsal** [comment]
The easier way for now is to make "memo" a soft keyword

**Comment by MatthieuDartiailh** [comment]
Sorry I missed this. I will try to see if I can come up with a more longterm fix.
