### ISSUE TITLE
Document repo contents

### ISSUE THREAD

**Issue by edemaine** [we-like-parsers/pegen#39]
Thanks to @pablogsal, [I just learned](https://mail.python.org/archives/list/python-dev@python.org/thread/UM7ANICTBDU3Q2DLKFZIK6C6OU3THKP4/) about the `data` directory which has some cool example grammars, including a Python port of `python.gram` &mdash; impressive!  It would have saved me a bunch of time for the README to link to the `data` directory, and for the `data` directory to have a README explaining what the various files are.

I could write a minimal PR but I don't know what most of the directories in this repo are (beyond the obvious `src/pegen`).

On the point of repo contents, I find the relation between this repo, the cpython edition, and the PyPI release confusing. Perhaps it would help to clarify that the intent is to keep this repo synchronized with the cpython edition (at least I get that impression from history), but there may be lag? Also, #1 suggests the latter doesn't exist, and in my limited testing, the PyPI edition seemed out-of-date; I could be wrong on that.

**Comment by pablogsal** [comment]
Hi @edemaine 👋 

Thanks a lot for opening the issue and I am glad that you found our work on the new PEG parser useful :)  I will try to make a PR today to add this information to the README. Alternatively, I can guide you on how to make a PR. What would you prefer?

> Also, #1 suggests the latter doesn't exist, and in my limited testing, the PyPI edition seemed out-of-date; I could be wrong on that.

The PyPI version should correspond to the latest release we did last month: https://github.com/we-like-parsers/pegen/releases/tag/v0.1.0

---------

By the way, I just recognize your photo! I used to be a Physics PHD before jumping to Computer Science and I remember with a lot of love the videos for your MIT courses about algorithms and data structures! Those lectures inspired me to start working more on computer science and to contribute to open source  (You should have a very old email from me from 2016 in your email account thanking you for them). I find it incredible that we meet again here after all these years, talking about the PEG parser and the new grammar that we made for (C)Python after all these years :)

**Comment by edemaine** [comment]
> I will try to make a PR today to add this information to the README. Alternatively, I can guide you on how to make a PR. What would you prefer?

I'd be happy to review a PR &mdash; I can give you an idea of how clear it is to an outsider. 🙂 

> I also make sure to sync it with the version we have in https://github.com/python/cpython/tree/main/Tools/peg_generator/pegen

That's great!  To be clear, I was saying that the README is confusing, so it'd be good to document this fact &mdash; I wasn't complaining about the situation itself. 🙂 

> I remember with a lot of love the videos for your MIT courses about algorithms and data structures!

Aww, thanks, and a funny coincidence indeed!  (Just found your old email.)  And very happy to have inspired you into open source development, something I've been pursuing more and more in recent years.

I just learned about the new PEG parser in the past week. It's very cool: really nice to use as a grammar designer, and some good algorithmic backing via memoization.  I'm excited to use it to build new languages; I can keep you posted on interesting developments.

**Comment by pablogsal** [comment]
Opened #42 to tacke this
