### ISSUE TITLE
Remove hard dependencies

### ISSUE THREAD

**Issue by MatthieuDartiailh** [we-like-parsers/pegen#53]
Currently we have hard dependencies on psutil, flask and flaks-wtf which seems completely overkill since one can perfectly use pegen without any of those.

**Comment by MatthieuDartiailh** [comment]
Looking in details at the use of each dependency:
- psutil is used in tests/utils and is already behind a try, except block. I believe it can simply be removed. We could add a 'memory' extra_requires though.
- flask and flask-wtf are used in the web.py module which provides a web based playground from reading quickly. Do we want to keep it ? @pablogsal  If we want to keep this making the dependency optional should not be a problem and allowing to access the module as an executable would make sense (pegen-web-playground ?). It may also duplicate some utilities but I did not check in details yet.

**Comment by pablogsal** [comment]
> Looking in details at the use of each dependency:
> - psutil is used in tests/utils and is already behind a try, except block. I believe it can simply be removed. We could add a 'memory' extra_requires though.
> - flask and flask-wtf are used in the web.py module which provides a web based playground from reading quickly. Do we want to keep it ? @pablogsal  If we want to keep this making the dependency optional should not be a problem and allowing to access the module as an executable would make sense (pegen-web-playground ?). It may also duplicate some utilities but I did not check in details yet.
> 

We can make flask and flask-wtf optional, as is not required for the core functionality of pegen. We can make this install under `pegen[web]` for example. Optionally we could even move this to a separate package, but they may be too much. What are your thoughts?

**Comment by MatthieuDartiailh** [comment]
I am fine having them under pegen[web] but I will audit the different helpers found in web.py. At first glance they look a lot like some testing helpers.

**Comment by MatthieuDartiailh** [comment]
True. If nobody beats me to it I will look into it but probably after dealing with improving the error reporting of the parser.

**Comment by lysnikolaou** [comment]
@MatthieuDartiailh Can we close this now?

**Comment by MatthieuDartiailh** [comment]
I believe so yes. Sorry I forgot to close it.
