### ISSUE TITLE
data/python_parser.py out of sync with data/python.gram

### ISSUE THREAD

**Issue by mw66** [we-like-parsers/pegen#61]
data/python.gram is updated 5 days ago, but not the data/python_parser.py

Since data/python_parser.py is generated, maybe we need a git hook to auto-gen data/python_parser.py whenever data/python.gram is updated.

BTW, the 1st release (0.1.0 Sep 6, 2021) is half year ago, are we planning to do a new release?

**Comment by MatthieuDartiailh** [comment]
I am personally not convinced we need to commit the generated parser but if we do it should up to date. Could you make a PR to take care of it ?

Regarding a new release, I would like to st least see #60 and a complete version of #41 or #48 in first.

**Comment by mw66** [comment]
I agree generated should not be checked in.

So, instead I add a demo target in Makefile to show how to use the tool.
