### ISSUE TITLE
Make a 2023 release

### ISSUE THREAD

**Issue by sodul** [we-like-parsers/pegen#79]
The latest, and only, release of pegen was v0.1.0 in 2021. There has been many commits and bug fixes since then. Are there any plans on creating a new release that will be available on [pypi.org](https://pypi.org/project/pegen/#history) soon?

**Comment by pablogsal** [comment]
Thanks for opening the issue!

I just published version 0.2.0 to pypi!

**Comment by sodul** [comment]
Thanks a lot for the super fast release!
