### ISSUE TITLE
Documentation: should C be mentioned

### ISSUE THREAD

**Issue by MatthieuDartiailh** [we-like-parsers/pegen#8]
Since one of the goal of the repo is to publish pegen on PyPI while including only the Python generator should the documentation mention C at all ?

 I am going through the docs and could make a PR to make the docs refer only to Python if that makes sense.

**Comment by MatthieuDartiailh** [comment]
Also helpers.md refers to thing that exist only in C. Some would probably make sense to be ported to Python, no ?

**Comment by pablogsal** [comment]
> Since one of the goal of the repo is to publish pegen on PyPI while including only the Python generator should the documentation mention C at all ?

No, we need to remove all references to the C parser.

> I am going through the docs and could make a PR to make the docs refer only to Python if that makes sense.

That would be fantastic. Please, feel free to add me as a reviewer to that PR : )

**Comment by MatthieuDartiailh** [comment]
See #10
